### ISSUE TITLE
env function confliction

### ISSUE THREAD

**Issue by daxiong123** [bixuehujin/blink#50]
PHP Fatal error:  Cannot redeclare env() (previously declared in /vendor/illuminate/support/helpers.php:606) in /vendor/blink/blink/src/support/helpers.php on line 121

**Comment by bixuehujin** [comment]
Which `illuminate/support` version are you using?

**Comment by daxiong123** [comment]
"illuminate/support": "5.5.*"

**Comment by bixuehujin** [comment]
This is because starting from laravel 5.4, `env()` function was moved into the `support` package.

I have submitted [a commit](https://github.com/bixuehujin/blink/commit/3375bfc47c4663a2d36b73e49d39646cc5f9bfa6) to avoid this confliction, and add a [new commit](https://github.com/bixuehujin/blink/commit/f8cb8d4c21390f83c4a565ed7e2fcfbc7bd8eab8) to make our `env()` function more compatible with laravel's.

This is not a good practice, so i may think to move all blink's helper functions into a namespace in the future.
